"""Generate SproutOS boot animation C data + animation timing.

Outputs the polyline point tables used by kernel.c's boot_animation().
Coordinate system: 1024x768 framebuffer.
"""
import textwrap

# === GEOMETRY (must match design_boot_logo.py) ========================
CX = 512
POT_CY = 565
POT_R = 118
STEM_TOP = 235
POT_TOP = POT_CY - POT_R

SEED = [
    (495, 580), (485, 560), (482, 540), (488, 522),
    (500, 514), (510, 522), (508, 545), (500, 570), (498, 582),
]

STEM = [
    (CX, POT_TOP + 12),
    (CX, 420), (CX, 380), (CX, 340),
    (CX, 305), (CX, 270), (CX, STEM_TOP),
]

ANT_BASE = (CX, STEM_TOP - 2)
ANT_TIP  = (CX, STEM_TOP - 60)
ANT_DISC = (CX, STEM_TOP - 73)
ANT_DISC_R = 11

LEFT_LEAF = [
    (CX - 2, 320), (CX - 35, 305), (CX - 80, 290), (CX - 130, 280),
    (CX - 175, 282), (CX - 200, 295), (CX - 195, 315), (CX - 165, 335),
    (CX - 120, 348), (CX - 70, 352), (CX - 25, 345), (CX - 2, 335),
]
RIGHT_LEAF = [(2 * CX - x, y) for (x, y) in LEFT_LEAF]

L_BRANCH_FROM = (CX - 60, 408)
L_BRANCH_TO   = (CX - 170, 408)
L_DISC        = (CX - 185, 408)
L_DISC_R      = 11

R_BRANCH_FROM = (CX + 60, 408)
R_BRANCH_TO   = (CX + 170, 408)
R_DISC        = (CX + 185, 408)
R_DISC_R      = 11


def emit_array(name, points):
    out = [f"static const int {name}[{len(points) * 2}] = {{"]
    for i, (x, y) in enumerate(points):
        end = "," if i < len(points) - 1 else ""
        out.append(f"    {x}, {y}{end}")
    out.append("};")
    out.append(f"#define {name}_LEN {len(points)}")
    return "\n".join(out)


print("// === Auto-generated by scripts/gen_boot_animation_data.py ===")
print("#pragma once")
print()
print(f"#define BOOT_LOGO_CX     {CX}")
print(f"#define BOOT_LOGO_POT_CY {POT_CY}")
print(f"#define BOOT_LOGO_POT_R  {POT_R}")
print(f"#define BOOT_LOGO_STEM_TOP_Y {STEM_TOP}")
print()
print(f"#define BOOT_LOGO_ANT_BASE_X {ANT_BASE[0]}")
print(f"#define BOOT_LOGO_ANT_BASE_Y {ANT_BASE[1]}")
print(f"#define BOOT_LOGO_ANT_TIP_X  {ANT_TIP[0]}")
print(f"#define BOOT_LOGO_ANT_TIP_Y  {ANT_TIP[1]}")
print(f"#define BOOT_LOGO_ANT_DISC_X {ANT_DISC[0]}")
print(f"#define BOOT_LOGO_ANT_DISC_Y {ANT_DISC[1]}")
print(f"#define BOOT_LOGO_ANT_DISC_R {ANT_DISC_R}")
print()
print(f"#define BOOT_LOGO_L_BRANCH_X0 {L_BRANCH_FROM[0]}")
print(f"#define BOOT_LOGO_L_BRANCH_Y0 {L_BRANCH_FROM[1]}")
print(f"#define BOOT_LOGO_L_BRANCH_X1 {L_BRANCH_TO[0]}")
print(f"#define BOOT_LOGO_L_BRANCH_Y1 {L_BRANCH_TO[1]}")
print(f"#define BOOT_LOGO_L_DISC_X {L_DISC[0]}")
print(f"#define BOOT_LOGO_L_DISC_Y {L_DISC[1]}")
print(f"#define BOOT_LOGO_L_DISC_R {L_DISC_R}")
print()
print(f"#define BOOT_LOGO_R_BRANCH_X0 {R_BRANCH_FROM[0]}")
print(f"#define BOOT_LOGO_R_BRANCH_Y0 {R_BRANCH_FROM[1]}")
print(f"#define BOOT_LOGO_R_BRANCH_X1 {R_BRANCH_TO[0]}")
print(f"#define BOOT_LOGO_R_BRANCH_Y1 {R_BRANCH_TO[1]}")
print(f"#define BOOT_LOGO_R_DISC_X {R_DISC[0]}")
print(f"#define BOOT_LOGO_R_DISC_Y {R_DISC[1]}")
print(f"#define BOOT_LOGO_R_DISC_R {R_DISC_R}")
print()

# Point arrays: x,y interleaved
print(emit_array("BOOT_LOGO_SEED_PTS", SEED))
print()
print(emit_array("BOOT_LOGO_STEM_PTS", STEM))
print()
print(emit_array("BOOT_LOGO_LEFT_LEAF_PTS",  LEFT_LEAF))
print()
print(emit_array("BOOT_LOGO_RIGHT_LEAF_PTS", RIGHT_LEAF))
print()

# Animation timing (in PIT ticks at 100 Hz → 1 tick = 10ms)
# Phase        | ticks | description
# -------------+-------+----------------------------------------
# PHASE_BLACK  |   20  | black pause (200ms)
# PHASE_POT    |   30  | pot circle (radial sweep, 30 frames)
# PHASE_STEM   |   25  | stem grows (25 segments)
# PHASE_LEAVES |   25  | leaves draw (left then right, 25 frames)
# PHASE_ANT    |   10  | top antenna (line + circle, 10 frames)
# PHASE_BRANCH |   15  | side branches (lines + circles, 15 frames)
# PHASE_SEED   |   10  | inner seed (10 frames)
# PHASE_TEXT   |   15  | "SproutOS v1.0" text fades in
# PHASE_HOLD   |   80  | hold final state (800ms)
print()
print("#define BOOT_PHASE_BLACK_TICKS    20")
print("#define BOOT_PHASE_POT_TICKS      30")
print("#define BOOT_PHASE_STEM_TICKS     25")
print("#define BOOT_PHASE_LEAVES_TICKS   25")
print("#define BOOT_PHASE_ANT_TICKS      10")
print("#define BOOT_PHASE_BRANCH_TICKS   15")
print("#define BOOT_PHASE_SEED_TICKS     10")
print("#define BOOT_PHASE_TEXT_TICKS     15")
print("#define BOOT_PHASE_HOLD_TICKS     80")
